
-- create
CREATE TABLE EMPLOYEE (
  empId INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  dept TEXT NOT NULL
);

-- insert
INSERT INTO EMPLOYEE VALUES (0001, 'Clark', 22);
INSERT INTO EMPLOYEE VALUES (0002, 'Dave', 45);
INSERT INTO EMPLOYEE VALUES (0003, 'Ava', 15);
INSERT INTO EMPLOYEE VALUES (0004, 'Sasha', 18);
INSERT INTO EMPLOYEE VALUES (0005, 'Anya', 32);
INSERT INTO EMPLOYEE VALUES (0006, 'David', 24);
INSERT INTO EMPLOYEE VALUES (0007, 'Andrey', 28);

-- fetch 
SELECT * FROM EMPLOYEE WHERE dept >=18;
